### ISSUE TITLE
region_code missing

### ISSUE THREAD

**Issue by jaunt** [ipdata/go#12]
Hello, thanks for this project.  Any reason region_code is missing?

Thanks

**Comment by theckman** [comment]
@jaunt likely completely unintentional. Would you have an interest in contributing that to the project?

**Comment by jaunt** [comment]
@theckman Yes.  It was a pretty simple change and seems to work fine.  Let me figure out how to make a pull request (I'm a newbie when it comes to contributing to open source projects).

**Comment by jonathan-kosgei** [comment]
Merged.
