### ISSUE TITLE
Add context to lookup

### ISSUE THREAD

**Issue by costela** [ipdata/go#14]
It's currently impossible to cancel lookups, so if we have some network issue between our system and ipdata, we might end up with a lot of "stuck" goroutines, even if we use circuit-breaking on our side.

It would be nice to have variants of `Lookup()` that take `context.Context` and pass it to the underlying `http.Request`.

**Comment by theckman** [comment]
@costela would you be able to raise a PR?

**Comment by obitech** [comment]
@theckman I've opened a PR :)
